ALTER SYSTEM SET "sec_case_sensitive_logon"=FALSE SCOPE=BOTH;
ALTER SYSTEM SET "_disable_highres_ticks"=TRUE SCOPE=SPFILE;
ALTER SYSTEM SET "_timer_precision"=2000 SCOPE=SPFILE;

SHUTDOWN IMMEDIATE

STARTUP MOUNT

ALTER DATABASE NOARCHIVELOG;

ALTER DATABASE OPEN;
