ALTER SESSION SET CONTAINER=ORCLPDB1;

CREATE TABLESPACE SBL_DATA DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/sbl_data_01.dbf' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED;
CREATE TABLESPACE SBL_INDX DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/sbl_indx_01.dbf' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED;
