ALTER SESSION SET CONTAINER=ORCLPDB1;

ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER SIEBEL IDENTIFIED BY oracle DEFAULT TABLESPACE SBL_DATA TEMPORARY TABLESPACE TEMP;
ALTER USER SIEBEL QUOTA UNLIMITED ON SBL_DATA;
ALTER USER SIEBEL QUOTA UNLIMITED ON SBL_INDX;

CREATE ROLE SSE_ROLE;
GRANT CREATE SESSION TO SSE_ROLE;

CREATE ROLE TBLO_ROLE;
GRANT ALTER SESSION, CREATE CLUSTER, CREATE INDEXTYPE,
  CREATE OPERATOR, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SESSION,
  CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW,
  CREATE DIMENSION, CREATE MATERIALIZED VIEW, QUERY REWRITE, ON COMMIT REFRESH
TO TBLO_ROLE;

GRANT SSE_ROLE TO SIEBEL;
GRANT TBLO_ROLE TO SIEBEL;

CREATE USER SADMIN IDENTIFIED BY oracle DEFAULT TABLESPACE SBL_DATA TEMPORARY TABLESPACE TEMP;
GRANT SSE_ROLE TO SADMIN;

CREATE USER LDAPUSER IDENTIFIED BY oracle DEFAULT TABLESPACE SBL_DATA TEMPORARY TABLESPACE TEMP;
GRANT SSE_ROLE TO LDAPUSER;

CREATE USER GUESTCST IDENTIFIED BY oracle DEFAULT TABLESPACE SBL_DATA TEMPORARY TABLESPACE TEMP;
GRANT SSE_ROLE TO GUESTCST;

CREATE USER GUESTERM IDENTIFIED BY oracle DEFAULT TABLESPACE SBL_DATA TEMPORARY TABLESPACE TEMP;
GRANT SSE_ROLE TO GUESTERM;
